title = "Axiomatic Semantics"
description = "Brute force solutions with proofs by intimidation"
base_url = "https://axiomatic.neophilus.net"
default_language = "en"

compile_sass = true

generate_feed = true

taxonomies = [
    {name = "tags"},
]

[markdown]
highlight_code = true
highlight_theme = "charcoal"
extra_syntaxes_and_themes = ["syntaxes"]
smart_punctuation = true

[extra.author]
name = "Tim DuBois"
